# Generated by Django 5.1.1 on 2024-11-10 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_imports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_from_provider", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("webhook_url", models.URLField(blank=True, default="")),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="data_imports.provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_from_provider", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "currency_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                ("balance", models.IntegerField()),
                ("goal", models.IntegerField(null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jars",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_from_provider", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("balance", models.IntegerField()),
                ("credit_limit", models.IntegerField()),
                ("type", models.CharField(max_length=14)),
                (
                    "currency_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                ("masked_pan", models.CharField(max_length=19)),
                ("iban", models.CharField(blank=True, default="", max_length=34)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "id_from_provider"),
                name="unique_profile_id_from_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_profile_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="jar",
            constraint=models.UniqueConstraint(
                fields=("profile", "id_from_provider"),
                name="unique_jar_id_from_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("profile", "id_from_provider"),
                name="unique_account_id_from_provider",
            ),
        ),
    ]
