# Generated by Django 4.2.16 on 2024-09-09 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_id", models.CharField(max_length=64)),
                ("token", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("webhook_url", models.URLField(blank=True, default="")),
                ("raw_data", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "currency_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                ("balance", models.IntegerField()),
                ("goal", models.IntegerField(null=True)),
                ("raw_data", models.JSONField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jars",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_id", models.CharField(max_length=64)),
                ("balance", models.IntegerField()),
                ("credit_limit", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("white", "White"),
                            ("platinum", "Platinum"),
                            ("iron", "Iron"),
                            ("fop", "Private Entrepreneur"),
                            ("yellow", "Yellow"),
                            ("eAid", "e-Aid"),
                            ("madeInUkraine", "Made in Ukraine"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "currency_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                (
                    "cashback_type",
                    models.CharField(
                        blank=True,
                        choices=[("UAH", "UAH"), ("Miles", "Miles")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("masked_pan", models.CharField(max_length=19)),
                ("iban", models.CharField(max_length=34)),
                ("raw_data", models.JSONField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("user", "mono_id"), name="unique_profile_mono_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("user", "token"), name="unique_profile_token"
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_profile_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="jar",
            constraint=models.UniqueConstraint(
                fields=("profile", "mono_id"), name="unique_jar_mono_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("profile", "mono_id"), name="unique_account_mono_id"
            ),
        ),
    ]
