# Generated by Django 5.1.1 on 2024-11-07 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_id", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("balance", models.IntegerField()),
                ("credit_limit", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("white", "White"),
                            ("platinum", "Platinum"),
                            ("iron", "Iron"),
                            ("fop", "Private Entrepreneur"),
                            ("yellow", "Yellow"),
                            ("eAid", "e-Aid"),
                            ("madeInUkraine", "Made in Ukraine"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "currency_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                (
                    "cashback_type",
                    models.CharField(
                        blank=True,
                        choices=[("UAH", "UAH"), ("Miles", "Miles")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("masked_pan", models.CharField(max_length=19)),
                ("iban", models.CharField(max_length=34)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("statement_last_updated", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Jar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "currency_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                ("balance", models.IntegerField()),
                ("goal", models.IntegerField(null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_id", models.CharField(max_length=64)),
                ("token", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField()),
            ],
        ),
    ]
