# Generated by Django 5.1.3 on 2024-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="credit_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
        migrations.AlterField(
            model_name="jar",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jar",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
