# Generated by Django 5.1.1 on 2024-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="webhook_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
