# Generated by Django 4.2.16 on 2024-09-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchantcategory",
            options={"verbose_name_plural": "Merchant categories"},
        ),
    ]
